function v = MakeTableSimCheck(t, so)
    tsl = size(t, 1); tsd = size(t, 2);
    dsl = size(so,1); dsd = size(so,2);

    if tsl ~= dsl
        error('Data length Unmatch')
    end

    vns = [  "Time", "Vdc", "Nrpm", "TrqReq" ...
            ,"IdReq", "IqReq", "IdOut", "IqOut" ...
            ,"VinVaM", "VinFwM", "VinVdM", "VinVqM" ...
            ,"VinVdMri", "VinVqMri", "VinVdMfq", "VinVqMfd" ...
            ,"VinVaC", "VinFwC", "VinVdC", "VinVqC" ...
            ,"VinVdCri", "VinVqCri", "VinVdCfq", "VinVqCfd" ...
            ,"IinVaM", "IinFwM", "IinVdM", "IinVqM" ...
            ,"IinVdMri", "IinVqMri", "IinVdMfq", "IinVqMfd" ...
            ,"IinVaC", "IinFwC", "IinVdC", "IinVqC" ...
            ,"IinVdCri", "IinVqCri", "IinVdCfq", "IinVqCfd" ...
            ,"VinFdM", "VinFqM", "IinFdM", "IinFqM" ...
            ,"VinFdC", "VinFqC", "IinFdC", "IinFqC" ...
            ];

    v = table('Size', [tsl, dsd+tsd] ...
        , 'VariableTypes',repmat("double", 1, dsd+tsd) ...
        , 'VariableNames',vns);
    v.Variables = [t, so];
end
